### ISSUE TITLE
Utilisation sous Debian (Buster)

### ISSUE THREAD

**Issue by clavay** [cedrick-f/pySyLiC#1]
Bonjour,

J'ai installé wxgtk3.0 (j'ai pas réussi à le lancer avec la version 2.8) et j'ai réussi à lancer PySyLiC en changeant dans Principal.py ligne 1965 sinon j'avais une erreur :
`size = (32,32)`
par
`size = (16,16)`

J'ai l'impression qu'il y a un soucis avec les icônes.
L'affichage n'est pas terrible :
![Capture d’écran de 2020-01-08 12-30-07](https://user-images.githubusercontent.com/38041007/71974784-a3600300-3212-11ea-971e-86f2e0f360ce.png)

Y a t il une solution pour avoir un affichage des icônes correct et la magouille que j'ai faite est elle bonne ?

Merci et bonne journée

**Comment by cedrick-f** [comment]
Bonjour
Pas terrible en effet ... mais le fait que pySyLiC se lance m'étonne déjà.
C'était quoi le message d'erreur avec des icônes en 32 ?

**Comment by clavay** [comment]
Il se lance mais tout ne fonctionne pas ensuite...
Il y a une manière de le faire tourner sur une machine linux récente avec des librairies récentes ?
Ou de faire un "executable" pour linux ? Via PyInstaller ?
Ou via docker ?

Avec 32 l'erreur c'est : 

Dossier de l'application : /home/clavay/Téléchargements/pySyLiC-0.39.0
Dossier des donnees /home/clavay/Téléchargements/pySyLiC-0.39.0
Fichier erreur : /home/clavay/Téléchargements/pySyLiC-0.39.0/pySyLiC.exe.log
Dossier Locale /home/clavay/Téléchargements/pySyLiC-0.39.0/locale
Langues installees : {'': u'D\xe9faut', 'fr': u'Fran\xe7ais', 'en': u'English'}
0.39
utf-8
user.home /home/clavay
defaut
ouverture : /home/clavay/Téléchargements/pySyLiC-0.39.0/PySyLiC.cfg
defaut
Traceback (most recent call last):
  File "PySylic.py", line 200, in <module>
    App = PySylicApp(0)
  File "/usr/lib/python2.7/dist-packages/wx-3.0-gtk3/wx/_core.py", line 8628, in __init__
    self._BootstrapApp()
  File "/usr/lib/python2.7/dist-packages/wx-3.0-gtk3/wx/_core.py", line 8196, in _BootstrapApp
    return _core_.PyApp__BootstrapApp(*args, **kwargs)
  File "PySylic.py", line 143, in OnInit
    frame = Principal.wxPySylic(None, nomFichier = NomFichier)
  File "/home/clavay/Téléchargements/pySyLiC-0.39.0/src/Principal.py", line 229, in __init__
    self.getFTBO, self.getFTBF, app = self)
  File "/home/clavay/Téléchargements/pySyLiC-0.39.0/src/Principal.py", line 1993, in __init__
    self.book.AssignImageList(self.imageList)
  File "/home/clavay/Téléchargements/pySyLiC-0.39.0/src/NotebookCtrl.py", line 5007, in AssignImageList
    self.nb.AssignImageList(imagelist)
  File "/home/clavay/Téléchargements/pySyLiC-0.39.0/src/NotebookCtrl.py", line 1567, in AssignImageList
    self._grayedlist.Add(newbmp)
  File "/usr/lib/python2.7/dist-packages/wx-3.0-gtk3/wx/_gdi.py", line 6735, in Add
    return _gdi_.ImageList_Add(*args, **kwargs)
wx._core.PyAssertionError: C++ assertion "(bitmap.GetWidth() >= m_width && bitmap.GetHeight() == m_height) || (m_width == 0 && m_height == 0)" failed at ../src/generic/imaglist.cpp(66) in Add(): invalid bitmap size in wxImageList: this might work on this platform but definitely won't under Windows.

**Comment by cedrick-f** [comment]
Je pense en effet que cette erreur ne devrait pas se produite maintenant.
pySyLiC mériterait de passer en python3, une mise à jour de tous les modules, d'être validé pour Linux et Mac, ... mais tout ça demande du temps, que je n'ai pas !
N'hésitez pas à faire un Fork :)
